[window]
decorations = "None"
opacity = 0.94
dynamic_title = true

[window.padding]
x = 12 # Equivalent to approx 1cell
y = 6  # Equivalent to approx 0.5cell

[font]
size = 13.0
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }

[font.offset]
y = 4 # Adjusts line_height to ~1.15

[cursor.style]
shape = "Block"
blinking = "Never"

[colors.primary]
background = "#1F1F28" # Kanagawa Base
foreground = "#DCD7BA"

[colors.cursor]
cursor = "#FFA066"
text = "#1F1F28"

[colors.selection]
background = "#FFA066"
text = "#1F1F28"

# Kanagawa (Gogh) palette bridge
[colors.normal]
black =   "#090618"
red =     "#C34043"
green =   "#76946A"
yellow =  "#C0A36E"
blue =    "#7E9CD8"
magenta = "#957FB8"
cyan =    "#6A9589"
white =   "#C8C093"

[colors.bright]
black =   "#727169"
red =     "#E82424"
green =   "#98BB6C"
yellow =  "#E6C384"
blue =    "#7FB4CA"
magenta = "#938AA9"
cyan =    "#7AA89F"
white =   "#DCD7BA"

[shell]
program = "fish"
